bounswe/bounswe2023group1

practice-app/backend/disasterresponse/pom.xml, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/controller/WeatherController.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/model/WeatherData.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/WeatherService.java
controller, service and model folders added.
WeatherController, WeatherService, WeatherData added.
pom.xml file updated
=> Weather Api

practice-app/frontend/disasterresponse/src/pages/DirectionsApi/DirectionsPage.css, practice-app/frontend/disasterresponse/src/pages/DirectionsApi/DirectionsPage.jsx
=> directions api frontend updated

practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/controller/DirectionsController.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/model/BookmarkedDestination.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/repository/BookmarkedDestinationRepository.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/DirectionsService.java, practice-app/frontend/disasterresponse/src/pages/DirectionsApi/DirectionsPage.jsx
BookmarkedDestination entity added and repository implemented, also GET and POST API endpoints added for it.
=> Directionsapi

practice-app/README.md, practice-app/docker-compose.yml, practice-app/docker-compose_dev.yml, practice-app/frontend/disasterresponse/Dockerfile, practice-app/frontend/disasterresponse/Dockerfile_dev, practice-app/frontend/disasterresponse/package.json, practice-app/frontend/disasterresponse/src/pages/DirectionsApi/DirectionsPage.jsx, practice-app/frontend/disasterresponse/src/pages/GoogleGeocodeApi/GoogleGeocodePage.jsx, practice-app/frontend/disasterresponse/src/pages/WeatherApi/WeatherPage.jsx, practice-app/nginx/default.conf, practice-app/nginx_dev/default.conf
Completed migration of project to nginx as per #184. The following changes were made:
- New docker container "webserver" added
- Migrated from npm start to nginx based static file hosting for production. For development, an alternative "docker-compose_dev.yml" exists with the previous npm start logic. To do frontend development more conveniently, use "docker-compose -f docker-compose_dev.yml up --build"
- Access the backend API calls are now through "/api/"
- The frontend Docker container was changed to only build the frontend and quit.
This pr shoulds resolve #180
=> Migrate to nginx

practice-app/backend/disasterresponse/Dockerfile, practice-app/backend/disasterresponse/src/main/resources/application.properties, practice-app/docker-compose.yml, practice-app/nginx/default.conf
Containerised backend build such that running `docker-compose up --build` now compiles the backend app.
=> Containerised backend build

practice-app/frontend/disasterresponse/src/pages/WeatherApi/WeatherPage.css, practice-app/frontend/disasterresponse/src/pages/WeatherApi/WeatherPage.jsx
getfeedback and givefeedback endpoints connected to frontend page. Css and Jsx files updated.
=> weather api frontend updated

practice-app/backend/disasterresponse/pom.xml, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/controller/TranslationController.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/model/TranslationData.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/TranslationService.java, practice-app/frontend/disasterresponse/src/App.js, practice-app/frontend/disasterresponse/src/pages/TranslationApi/GoogleTranslationPage.css, practice-app/frontend/disasterresponse/src/pages/TranslationApi/GoogleTranslationPage.jsx
I implemented Google Translation API.
=> Translation api

practice-app/docker-compose_dev.yml, practice-app/nginx_dev/default.conf
=> Hotfix: make docker dev build work again

practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/model/BookmarkedDestination.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/DirectionsService.java, practice-app/backend/disasterresponse/src/test/java/com/a1/disasterresponse/service/DirectionsServiceTest.java
DirectionsServiceTest class created and implemented test cases for GET & POST requests.
=> Directionsapi test cases

practice-app/backend/disasterresponse/src/main/resources/application.properties, practice-app/nginx/default.conf, practice-app/nginx_dev/default.conf
Fixed swagger issues #203 #190
=> Fix swagger

practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/controller/MovieController.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/model/WatchedItem.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/repository/WatchedItemRepository.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/MovieService.java, practice-app/frontend/disasterresponse/src/pages/ImdbApi/ImdbPage.css, practice-app/frontend/disasterresponse/src/pages/ImdbApi/ImdbPage.jsx
Created the endpoint using post method, implemented the frontend
=> Movie post endpoint

practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/controller/GeoJsController.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/GeoJsService.java, practice-app/backend/disasterresponse/src/test/java/com/a1/disasterresponse/service/GeoJsServiceTest.java
=> Added tests.

practice-app/backend/disasterresponse/Dockerfile, practice-app/docker-compose.yml, practice-app/frontend/disasterresponse/Dockerfile
These changes fix the issues with deployment, specifically the frontend not standing up in the server.
=> Fix deployment

practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/controller/NASAImageController.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/model/NasaData.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/repository/NasaDataRepository.java, practice-app/backend/disasterresponse/src/main/java/com/a1/disasterresponse/service/NASAImageService.java, practice-app/backend/disasterresponse/src/test/java/com/a1/disasterresponse/service/NASAImageTest.java, practice-app/frontend/disasterresponse/src/App.js, practice-app/frontend/disasterresponse/src/pages/NASAImageApi/NasaImage.js
=> Nasaapi end

resq/backend/resq/pom.xml, resq/backend/resq/src/main/java/com/groupa1/resq/config/ModelMapperConfig.java, resq/backend/resq/src/main/java/com/groupa1/resq/controller/UserController.java, resq/backend/resq/src/main/java/com/groupa1/resq/converter/UserConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/dto/UserDto.java
=> #314 Implemented get user info endpoint.

resq/frontend/src/App.js, resq/frontend/src/components/ImageUpload.js, resq/frontend/src/pages/Account.js, resq/frontend/src/pages/RoleRequest.js, resq/frontend/src/pages/UserRoles.js
responder verification. id upload required
=> responder verification. id upload required

resq/mobile/ResQ/app/build.gradle.kts, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/MainActivity.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/MapScreen.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/RequestScreen.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/utils/NavigationItem.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/MapViewModel.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/RequestViewModel.kt
Map view is built without the map implementation ,
Navigation to request screen is implemented,
Request UI  is created
=> Request Screen and Navigation

resq/backend/resq/src/main/java/com/groupa1/resq/auth/UserDetailsImpl.java, resq/backend/resq/src/test/java/com/groupa1/resq/service/AuthServiceTest.java
=> #318 Unit tests for AuthService completed with 100% coverage.

resq/frontend/src/App.js, resq/frontend/src/pages/RoleRequest.js, resq/frontend/src/pages/UserRoles.js
add state for selected role and make a page that is only visible to responders
=> show spesific pages to users based on chosen role

resq/backend/resq/src/main/java/com/groupa1/resq/service/CategoryTreeNodeService.java, resq/backend/resq/src/test/java/com/groupa1/resq/service/CategoryTreeNodeServiceTest.java
=> #318 Unit tests for CategoryTreeNodeService completed.

resq/backend/resq/src/test/java/com/groupa1/resq/service/NeedServiceTest.java, resq/backend/resq/src/test/java/com/groupa1/resq/service/RequestServiceTest.java
=> Need-Request unit tests are implemented.

resq/backend/resq/src/main/java/com/groupa1/resq/config/TreeInitializationService.java, resq/backend/resq/src/main/java/com/groupa1/resq/controller/CategoryTreeNodeController.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/CategoryTreeNode.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/CategoryTreeNodeService.java, resq/backend/resq/src/main/resources/category-tree.json
The category tree is finalized. I added endpoints to get the whole tree as JSON. 
In addition, backend developers must add a field to appparam.txt as:
category-tree.reset=true
First, run the app with this config. It will reset the category tree in the database. Later, you can change it to 
category-tree.reset=false.
Since it is reading the tree from a json file named as category-tree.json, if we later change the initial tree structure, we can easily update our databases with this property field in our config file.
=> #297 Finalized the category tree.

resq/frontend/src/components/AccountProfile.js, resq/frontend/src/pages/MapDemo.js
This pull request adds the functionality of Google Reverse Geocoding to the project, enhancing the display of locations in a more human-readable format. The integration utilizes the latitude and longitude coordinates associated with each location, fetching corresponding place names.
- Implemented reverse geocoding for converting latitude and longitude to human-readable locations.
- The API key for Google Reverse Geocoding is securely managed and stored.
- This feature contributes to a more user-friendly presentation of location information across the application.
=> Added Google Reverse Geocoding for Displaying Locations in human readable format

resq/frontend/package.json, resq/frontend/src/App.js, resq/frontend/src/components/MapDataGrid.js, resq/frontend/src/pages/MapDemo.js, resq/frontend/src/pages/SignIn.js, resq/frontend/src/pages/SignUp.js
Logout problem fixed.
[#353 ](https://github.com/bounswe/bounswe2023group1/issues/353)
=> Frontend Login and SignUp Process with Backend-Driven Feedback

resq/frontend/src/components/MapDataGrid.js, resq/frontend/src/pages/MapDemo.js
- **Streamlined Resource Display:** The new data table is meticulously designed to present resource information in a structured and easily digestible format. This includes key columns such as Name, Quantity, Type, and Location, enabling users to get a comprehensive overview at a glance.
- **Robust Filtering Mechanism:** A standout feature of this implementation is the advanced filtering functionality. Users can now effortlessly filter resources based on various parameters, significantly reducing the time and effort required to locate specific resource information.
- **Enhanced User Experience:** The intuitive interface and responsive design of the data table ensure that users can navigate and find the needed resources with ease and precision, thereby improving overall productivity and …
=> Implement Enhanced Resource Data Table with Advanced Filtering Features

resq/backend/resq/src/main/java/com/groupa1/resq/controller/ResourceController.java, resq/backend/resq/src/main/java/com/groupa1/resq/exception/GeneralExceptionHandler.java, resq/backend/resq/src/main/java/com/groupa1/resq/repository/ResourceRepository.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/CreateResourceRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ResourceService.java, resq/backend/resq/src/main/java/com/groupa1/resq/specification/ResourceSpecifications.java
CRUD operations, filter by category, filter by distance endpoints are implemented. I believe more endpoints may be needed as frontend starts to use them. If frontend demand more functionality, they should be implemented then.
note that that the branch should have been finalizing-resource-api
=> Resource API enhancement

resq/backend/resq/src/main/java/com/groupa1/resq/controller/NotificationController.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Action.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/BaseEntity.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Feedback.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Need.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Notification.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Request.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Resource.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Task.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/User.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/enums/ENotificationEntityType.java, resq/backend/resq/src/main/java/com/groupa1/resq/repository/NotificationRepository.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/CreateReqRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/CreateResourceRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/CreateTaskRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/response/ResourceResponse.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ActionService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/NotificationService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/RequestService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ResourceService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/TaskService.java, resq/backend/resq/src/main/java/com/groupa1/resq/util/NotificationMessages.java
Closes #396 NotificationService implemented and some database relations together with their service classes refactored. Later, Firebase implementation will be added for Push Notification.
It would be good for backend devs to check the changed parts. Here are some changes and reasons:
* Adding @EqualsAndHashCode to some entities -> Since we use HashSet to collect them at some point, it is necessary to override their equals and hashcode methods.
* @PrePersist works before insertion to the table, so it saves the creation and modification time at the insertion time. In addition, @PreUpdate works before modification to the record, so it saves the modification time at each update to the record.
* In CreateReqRequest class, changed Set<Needs> needs to Set<Long> needIds, since it is enough to get …
=> #396 Notification Service and Database Implementation

resq/frontend/src/App.js, resq/frontend/src/components/RequestReview.js, resq/frontend/src/pages/RequestCreation.js
Enhanced Aid Distribution with New 'Request Review & Summary' Page
This PR introduces a crucial 'Request Review & Summary' page, streamlining the process of distributing aid. It leverages React and Material UI for a clear presentation of needs, addresses, and recurring requirements.
Features:
Dynamic display of aid requests.
Clear address formatting.
Section for ongoing needs.
Improvements:
Fine-tuned data display.
Recurrent needs emphasis
"A comprehensive summary at the final checkout stage enables users to review all their requested needs in detail. This allows for a thorough examination, ensuring that no aspect is overlooked. If a user identifies any missing elements, they can easily revert to previous steps to make the necessary revisions, without the risk of losing any previously …
=> Enhance Aid Distribution with New 'Request Review & Summary' Page

resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/MainActivity.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/theme/Color.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/SettingsScreen.kt
Settings Screen created
Logout implementation added
=> Logout Implementation

resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/MainActivity.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/MapScreen.kt
Guest view implemented. Now user's can see map without login.
Also when a user logout it will navigate to guest view again
=> Guest View Implementation and Navigation

resq/backend/resq/src/main/java/com/groupa1/resq/converter/NeedConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/converter/RequestConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/converter/ResourceConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/dto/NeedDto.java, resq/backend/resq/src/main/java/com/groupa1/resq/dto/RequestDto.java, resq/backend/resq/src/main/java/com/groupa1/resq/dto/ResourceDto.java, resq/backend/resq/src/main/java/com/groupa1/resq/response/ActionResponse.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ActionService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ResourceService.java
Added the creation date to resource, action, request, need objects.
=> created at added to action, resource, request, need

resq/backend/resq/src/main/java/com/groupa1/resq/controller/ResourceController.java
=> #476 Victim shall be able to view resources.

resq/frontend/src/App.js, resq/frontend/src/components/ResourceAddress.js, resq/frontend/src/pages/ResourceCreation.js
Resource creation is a priority for this platform since resource management is one of the most crucial points. This pr tries to solve:
1.1.2.2.2. Responders shall be able to create a resource for objects or services they can offer.
1.1.2.2.3. Responders shall be able to set the following information regarding a resource: location, quantity, type, category
So, resources can be material & human resources.
And resources should have those informations: location, quantity, type, category.
Also, with the focus on resource management, this pr tries to solve:
1.2.3. Resource Management
1.2.3.1. Digital Resources
1.2.3.1.2. Resources must be digitized and quantified in the system. -> quantification is done.
1.2.3.2. Categorization of resources -> categorization is done.
1.2.3.2.1. To facilitate …
=> Resource Creation is implemented with respect to requirements. 

resq/backend/resq/src/main/java/com/groupa1/resq/security/WebSecurityConfig.java
Closes #484 Problem fixed with default CORS configuration. Frontend should check if there is any additional problem.
=> #484 Default CORS Configuration is added.

resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/data/remote/ResqService.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/ProfileScreen.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/ProfileViewModel.kt
=> Request Role Implementation

resq/mobile/ResQ/app/build.gradle.kts, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/data/models/Profile.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/data/remote/ResqService.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/theme/Color.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/ProfileScreen.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/ProfileViewModel.kt
Reverts bounswe/bounswe2023group1#498
=> Revert "Feature/mobile 360 update user profiles"

resq/frontend/src/App.js, resq/frontend/src/AppService.js, resq/frontend/src/CategoryTree.js, resq/frontend/src/components/Resource/ResourceAddress.js, resq/frontend/src/components/Resource/ResourceContext.js, resq/frontend/src/components/Resource/ResourceCreation.js, resq/frontend/src/components/Resource/ResourceDetail1.js, resq/frontend/src/components/Resource/ResourceDetail2.js, resq/frontend/src/pages/MapPage.js, resq/frontend/src/pages/ResourceCreation.js, resq/frontend/src/pages/SignIn.js
Backend integration is further implemented since the information gathered at frontend for resource is much more detailed and comprehensive, and backend asks for limited number of information at its need body, some adjustments were needed.
=> Backend integration for resource creation is further implemented

README.md, resq/README.md, resq/backend/resq/docker-compose.yml, resq/frontend/Dockerfile
Added a docker container that runs the frontend locally. Further added a readme for the code that explains how to run the code.
=> Dockerise frontend and add global readme file

resq/.idea/.gitignore, resq/.idea/misc.xml, resq/.idea/modules.xml, resq/.idea/resq.iml, resq/.idea/vcs.xml, resq/frontend/src/components/AnnotationCard.js, resq/frontend/src/components/Cards/AnnotationCard.js, resq/frontend/src/components/Resource/ResourceAddress.js, resq/frontend/src/pages/MapPage.js
This Pull Request addresses critical issues related to the Map Page becoming unresponsive after interacting with the "View More" button on the Annotation Cards. Additionally, it enhances the functionality and reliability of displaying long descriptions in the Annotation Cards.
1. **Map Page Unresponsiveness**: Users experienced a lack of responsiveness on the Map Page after the initial click on the "View More" button within the Annotation Cards. This issue was traced back to complex state management and rendering logic in the `MapPage` component.
2. **Annotation Card Long Description Display**: The long descriptions in the Annotation Cards were not consistently appearing as intended. This was due to suboptimal state synchronization and event handling within the component.
1. **Optimizing …
=> Fix Unresponsiveness on Map Page and Enhance Annotation Card Functionality

resq/backend/resq/src/main/java/com/groupa1/resq/controller/ActionController.java, resq/backend/resq/src/main/java/com/groupa1/resq/controller/ResourceController.java, resq/backend/resq/src/main/java/com/groupa1/resq/controller/TaskController.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/enums/EUserRole.java, resq/backend/resq/src/main/java/com/groupa1/resq/repository/ActionRepository.java, resq/backend/resq/src/main/java/com/groupa1/resq/repository/TaskRepository.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/UpdateActionRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/UpdateTaskRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ActionService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ResourceService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/TaskService.java, resq/backend/resq/src/main/java/com/groupa1/resq/specification/ActionSpecifications.java, resq/backend/resq/src/main/java/com/groupa1/resq/specification/ResourceSpecifications.java, resq/backend/resq/src/main/java/com/groupa1/resq/specification/TaskSpecifications.java, resq/backend/resq/src/main/java/com/groupa1/resq/util/NotificationMessages.java
The mainly coordinator related functionalities are added to the Action, Resource and Task Controller:
-Update Action (Coordinator)
-Delete Action (Coordinator)
-View Action by Filter (Coordinator)
-Verify Action (Facilitator)
-Resource Rectangular Location Filtering (Coordinator/Responder/Victim)
-Update Task (Coordinator)
-View Task by Filter (Coordinator)
Fix:
-ADMIN enum type is added to the EUserType class.
=> Improved/Added coordinator functionalities.

resq/backend/resq/src/main/java/com/groupa1/resq/controller/NotificationController.java, resq/backend/resq/src/main/java/com/groupa1/resq/controller/UserController.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/enums/EUserRole.java, resq/backend/resq/src/main/java/com/groupa1/resq/exception/EntityNotAllowedException.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/UserService.java, resq/backend/resq/src/main/java/com/groupa1/resq/util/NotificationMessages.java
Admin functionalities are added:
-Give role to given user (Admin/Coordinator/Facilitator).
-Remove role to given user (Admin/Coordinator/Facilitator).
-Send system notification to other admins (Admin).
=> Improved/Added admin functionalities.

resq/frontend/src/components/Resource/ResourceDetail1.js
**_Overview:_**
This Pull Request introduces significant updates to the ResourceDetails1 component, enhancing the resource type selection functionality. The key improvements focus on integrating category tree data for both material and human resources and refining the user interaction process.
**_Key Updates:_**
Exclusive Selection Logic: Implemented logic to exclusively select either a material or a human resource. Selecting one type automatically deselects the other, ensuring that only one resource type can be chosen at any given time.
State Management Improvements: The component's state management was updated to effectively handle the new selection logic. This includes using state hooks to track the user's selection and updating the UI accordingly.
Updated useQuery Calls: Modified the …
=> Address the Deficiency at Resource Type and Resource Selection Logic in ResourceDetails1 Component

resq/frontend/src/components/Resource/ResourceCreation.js, resq/frontend/src/components/Resource/ResourceDetail3.js
We need photos for clarification, for people who don't know reading and especially for the customer because they have requested it. So that we will be able to annotate our images and will be experienced at this topic.
=> Implementation - First Draft of - Customer Request - Add Components as Images To be Annotated to Resources 

resq/backend/resq/src/main/java/com/groupa1/resq/converter/NeedConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/converter/ResourceConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/enums/EGender.java
NullPointerException handled in Need and Resource entities. In addition, EGender's two fields changed back to the old version. Closes #592
=> #592 NullPointerException handled

resq/backend/resq/src/main/java/com/groupa1/resq/service/AuthService.java
=> Role prefix removed

resq/backend/resq/pom.xml, resq/backend/resq/src/main/java/com/groupa1/resq/config/AmazonClient.java, resq/backend/resq/src/main/java/com/groupa1/resq/controller/ResourceController.java, resq/backend/resq/src/main/java/com/groupa1/resq/converter/ResourceConverter.java, resq/backend/resq/src/main/java/com/groupa1/resq/dto/FileDto.java, resq/backend/resq/src/main/java/com/groupa1/resq/dto/ResourceDto.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/File.java, resq/backend/resq/src/main/java/com/groupa1/resq/entity/Resource.java, resq/backend/resq/src/main/java/com/groupa1/resq/repository/FileRepository.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/CreateNeedRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/CreateResourceRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/request/UpdateNeedRequest.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/NeedService.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ResourceService.java
Image upload implemented using Amazon s3 bucket. A new entity called File persisted in the database to keep the file info in the database. Actual file is stored in s3. To get the image, frontend/mobile should take the resourceDto, which includes fileDto, which includes the file url. Then, they can view the image.
=> #591 Implemented Image upload to resources using amazon s3 bucket.

resq/backend/resq/src/main/java/com/groupa1/resq/controller/ResourceController.java, resq/backend/resq/src/main/java/com/groupa1/resq/service/ResourceService.java, resq/backend/resq/src/main/java/com/groupa1/resq/specification/ResourceSpecifications.java
Resource controller's two filtering functions (FilterByCategory & FilterByCategoryRectangularScope) is improved with adding filtering support for receiver id.
=> Filtering Resource by Receiver Id

resq/backend/resq/src/main/java/com/groupa1/resq/controller/NeedController.java
=> #612 Victims allowed to use some endpoints in NeedController.

resq/frontend/src/App.js
- When facilitator requests for a role and it is approved, topbar will show facilitator panel to the user. 
- And same logic also applied for victim.
=> Topbar Edited to Show Role Based Panel View

resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/MainActivity.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/data/models/Task.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/data/remote/ResqService.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/OngoingTasksScreen.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/MyRequestsViewModel.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/OngoingTasksViewModel.kt
- Ongoing Tasks implemented.
- service for MyTasks written
- Suspend was necessary in MyRequestsViewModel so it is removed.
=> - OngoingTasksScreen updated according to backend

resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/TasksViewModel.kt
I accidentally deleted this file
=> Fix my mistake

resq/backend/resq/src/test/java/com/groupa1/resq/service/NotificationServiceTest.java, resq/backend/resq/src/test/java/com/groupa1/resq/service/ResourceServiceTest.java
Adds:
-4 unit tests for the NotificationService.
-7 unit tests for the ResourceService.
=> Missing unit tests for Resource & Notification Service

resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/MainActivity.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/data/remote/ResqService.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/ui/views/screens/MyRequestsScreen.kt, resq/mobile/ResQ/app/src/main/java/com/cmpe451/resq/viewmodels/MyRequestsViewModel.kt
- Users can delete their requests with the update
=> Update My Requests Page

resq/frontend/src/AppService.js, resq/frontend/src/components/Cards/TaskCard.js, resq/frontend/src/pages/TaskSelectPage.js
As per #633 , the ability to see which actions he has completed so far and set them as done was added. Furthermore, the set task complete button now appears only when all actions are complete.
=> add checkboxes to display and set action status
